const product = [
    {
        id:1,
        Name: "The Signature Double",
        details: "Two smashed beef patties, house sauce, caramelized onions, american cheese on a toasted",
        price: "12.99",
        img:"image/p1.png",
        type:"featured",
        cat:"",
    },
    {
        id:2,
        Name: "Margherita Classico",
        details: "San Marzano tomato sauce, fresh mozzarella di bufala, basil, extra",
        price: "16.50",
        img:"image/p2.png",
        type:"featured",
        cat:"",
    },
    {
        id:3,
        Name: "Spicy Tuna Crunch",
        details: "Fresh yellowfin tuna, spicy mayo, cucumber, topped with tempura",
        price: "14.00",
        img:"image/p3.png",
        type:"featured",
        cat:"",
    },
    {
        id:4,
        Name: "Al Pastor Tacos (3)",
        details: "Marinated pork shoulder, grilled pineapple, white onion, cilantro, on fresh corn tortillas.",
        price: "11.50",
        img:"image/p4.png",
        type:"featured",
        cat:"",
    },
    {
        id:5,
        Name: "Molten Chocolate Lava",
        details: "Warm, rich chocolate cake with a molten center, served with a side of",
        price: "9.00",
        img:"image/p5.png",
        type:"",
        cat:"",
    },
    {
        id:6,
        Name: "Harvest Quinoa Bowl",
        details: "Two smashed beef patties, house sauce, caramelized onions, american cheese on a toasted",
        price: "19.00",
        img:"image/p6.png",
        type:"",
        cat:"",
    },
    {
        id:7,
        Name: "Truffle Parmesan Fries",
        details: "Two smashed beef patties, house sauce, caramelized onions, american cheese on a toasted",
        price: "16.00",
        img:"image/p7.png",
        type:"",
        cat:"",
    },
    {
        id:8,
        Name: "Artisan Iced Latte",
        details: "Two smashed beef patties, house sauce, caramelized onions, american cheese on a toasted",
        price: "7.56",
        img:"image/p8.png",
        type:"",
        cat:"",
    },
    {
        id:9,
        Name: "Luigi's Oven",
        details: "Two smashed beef patties, house sauce, caramelized onions, american cheese on a toasted",
        price: "1.99",
        img:"image/p9.png",
        type:"",
        cat:"",
    },
    {
        id:10,
        Name: "The Signature Double",
        details: "Two smashed beef patties, house sauce, caramelized onions, american cheese on a toasted",
        price: "12.99",
        img:"image/p10.png",
        type:"",
        cat:"",
    },
    {
        id:11,
        Name: "The Signature Double",
        details: "Two smashed beef patties, house sauce, caramelized onions, american cheese on a toasted",
        price: "12.99",
        img:"image/p11.png",
        type:"",
        cat:"",
    },
    {
        id:12,
        Name: "The Signature Double",
        details: "Two smashed beef patties, house sauce, caramelized onions, american cheese on a toasted",
        price: "12.99",
        img:"image/p12.png",
        type:"",
        cat:"",
    },
]